import { bankLogos } from "../getBankNameFromCardNumber/logos";

/** Iranian IBAN bank-code to packaged SVG logo mapping. */
export const ibanBankLogo: ReadonlyMap<string, string> = new Map([
	["010", bankLogos.BankMarkazi],
	["011", bankLogos.SanatMadan],
	["012", bankLogos.Mellat],
	["013", bankLogos.Refah],
	["014", bankLogos.Maskan],
	["015", bankLogos.Sepah],
	["016", bankLogos.Keshavarzi],
	["017", bankLogos.Melli],
	["018", bankLogos.Tejarat],
	["019", bankLogos.Saderat],
	["020", bankLogos.ToseeSaderat],
	["021", bankLogos.Postbank],
	["022", bankLogos.ToseeTaavon],
	["051", bankLogos.Tosee],
	["052", bankLogos.Ghavamin],
	["053", bankLogos.Karafarin],
	["054", bankLogos.Parsian],
	["055", bankLogos.EghtesadNovin],
	["056", bankLogos.Saman],
	["057", bankLogos.Pasargad],
	["058", bankLogos.Sarmayeh],
	["059", bankLogos.Sina],
	["060", bankLogos.MehrIran],
	["061", bankLogos.Shahr],
	["062", bankLogos.Ayandeh],
	["063", bankLogos.Ansar],
	["064", bankLogos.Gardeshgari],
	["065", bankLogos.Hekmat],
	["066", bankLogos.Dey],
	["069", bankLogos.IranZamin],
	["070", bankLogos.Resalat],
	["073", bankLogos.Kosar],
	["075", bankLogos.Melall],
	["078", bankLogos.KhavarMianeh],
	["079", bankLogos.MehrEghtesad],
	["080", bankLogos.Noor],
	["090", bankLogos.MehrIran],
	["095", bankLogos.IranVenezuela],
]);
