import config from "../../config/index";
const baseUrl = config.baseUrl;
export const bankData: Record<string, { name: string; logo: string }> = {
	"627412": { name: "بانک اقتصاد نوین", logo: `${baseUrl}/Eghtesad_Novin.svg` },
	"627381": { name: "بانک (سپه) انصار", logo: `${baseUrl}/Ansar.svg` },
	"505785": { name: "بانک ایران زمین", logo: `${baseUrl}/Iran_Zamin.svg` },
	"622106": { name: "بانک پارسیان", logo: `${baseUrl}/Parsian.svg` },
	"639194": { name: "بانک پارسیان", logo: `${baseUrl}/Parsian.svg` },
	"627884": { name: "بانک پارسیان", logo: `${baseUrl}/Parsian.svg` },
	"639347": { name: "بانک پاسارگاد", logo: `${baseUrl}/Pasargad.svg` },
	"502229": { name: "بانک پاسارگاد", logo: `${baseUrl}/Pasargad.svg` },
	"636214": { name: "بانک آینده", logo: `${baseUrl}/Ayandeh.svg` },
	"627353": { name: "بانک تجارت", logo: `${baseUrl}/Tejarat.svg` },
	"585983": { name: "بانک تجارت", logo: `${baseUrl}/Tejarat.svg` },
	"502908": { name: "بانک توسعه تعاون", logo: `${baseUrl}/Tosee_Taavon.svg` },
	"627648": {
		name: "بانک توسعه صادرات ایران",
		logo: `${baseUrl}/Tosee_Saderat.svg`,
	},
	"207177": {
		name: "بانک توسعه صادرات ایران",
		logo: `${baseUrl}/Tosee_Saderat.svg`,
	},
	"636949": { name: "بانک حکمت ایرانیان (سپه)", logo: `${baseUrl}/Hekmat.svg` },
	"502938": { name: "بانک دی", logo: `${baseUrl}/Dey.svg` },
	"589463": { name: "بانک رفاه کارگران", logo: `${baseUrl}/Refah.svg` },
	"621986": { name: "بانک سامان", logo: `${baseUrl}/Saman.svg` },
	"589210": { name: "بانک سپه", logo: `${baseUrl}/Sepah.svg` },
	"639607": { name: "بانک سرمایه", logo: `${baseUrl}/Sarmayeh.svg` },
	"639346": { name: "بانک سینا", logo: `${baseUrl}/Sina.svg` },
	"502806": { name: "بانک شهر", logo: `${baseUrl}/Shahr.svg` },
	"504706": { name: "بانک شهر", logo: `${baseUrl}/Shahr.svg` },
	"603769": { name: "بانک صادرات ایران", logo: `${baseUrl}/Saderat.svg` },
	"627961": { name: "بانک صنعت و معدن", logo: `${baseUrl}/Sanat_Madan.svg` },
	"606373": {
		name: "بانک قرض الحسنه مهر ایران",
		logo: `${baseUrl}/Mehr_Iran.svg`,
	},
	"639599": { name: "بانک (سپه) قوامین", logo: `${baseUrl}/Ghavamin.svg` },
	"627488": { name: "بانک کارآفرین", logo: `${baseUrl}/Karafarin.svg` },
	"502910": { name: "بانک کارآفرین", logo: `${baseUrl}/Karafarin.svg` },
	"603770": { name: "بانک کشاورزی", logo: `${baseUrl}/Keshavarzi.svg` },
	"639217": { name: "بانک کشاورزی", logo: `${baseUrl}/Keshavarzi.svg` },
	"505416": { name: "بانک گردشگری", logo: `${baseUrl}/Gardeshgari.svg` },
	"505426": { name: "بانک گردشگری", logo: `${baseUrl}/Gardeshgari.svg` },
	"636795": {
		name: "بانک مرکزی جمهوری اسلامی ایران",
		logo: `${baseUrl}/Bank_Markazi.svg`,
	},
	"628023": { name: "بانک مسکن", logo: `${baseUrl}/Maskan.svg` },
	"610433": { name: "بانک ملت", logo: `${baseUrl}/Mellat.svg` },
	"991975": { name: "بانک ملت", logo: `${baseUrl}/Mellat.svg` },
	"603799": { name: "بانک ملی ایران", logo: `${baseUrl}/Melli.svg` },
	"639370": {
		name: "بانک مهر اقتصاد (سپه)",
		logo: `${baseUrl}/Mehr_Eghtesad.svg`,
	},
	"627760": { name: "بانک پست ایران", logo: `${baseUrl}/Postbank.svg` },
	"628157": { name: "موسسه اعتباری توسعه", logo: `${baseUrl}/Tosee.svg` },
	"505801": { name: "(سپه) موسسه اعتباری کوثر", logo: `${baseUrl}/Kosar.svg` },
	"606256": { name: "موسسه اعتباری ملل", logo: `${baseUrl}/Melall.svg` },
	"504172": { name: "بانک رسالت", logo: `${baseUrl}/Resalat.svg` },
	"507677": { name: "موسسه نور", logo: `${baseUrl}/Noor.svg` },
	"585947": { name: "بانک خاورمیانه", logo: `${baseUrl}/Khavar_Mianeh.svg` },
};
